### ISSUE TITLE
Mishandling of tokens for custom text

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/views_send#5]
A field can be used as a token in the 'To' field for an email, except where it is a custom text field comprising two other fields. For example, if we have separate fields for [firstname] and [surname] and then combine them as [fullname] in a custom field, we can use this custom field in the body of the email but it does not work in the to field. In the example below the two fields are [field_first_name] and [field_name] and these are joined together in [views-send:custom_text] which works correctly as a token in the body of the email but not in the 'To' field.

![test views send - www oliverweb net 2016-01-14 06-36-13](https://cloud.githubusercontent.com/assets/10559274/12317578/55ceb702-ba8a-11e5-8396-05aff930694e.png)

**Comment by Graham-72** [comment]
See also Drupal issue at https://www.drupal.org/node/1833608.

**Comment by klonos** [comment]
@Graham-72 oh maaan!! I thought you'd have learned by now but you keep doing it and I got sick of fixing your releases' titles. Just joking, :smiling_imp: 

But FYI, I believe that the common practice is to have the release title be project name + version so that it shows nicely in the GitHub notifications. You are in the habit of using it for a description instead. I fixed it (yet again) for you:

![backdrop-contrib-views_send-release_description_fixed](https://cloud.githubusercontent.com/assets/2423362/12370279/63361bac-bc5f-11e5-931a-db8277ed16f0.png)

**Comment by Graham-72** [comment]
Hi @klonos Thank you for helping me yet again. I will try to get this into my thick head!. There is so much to remember and my grey cells are dying out. :smile:

**Comment by klonos** [comment]
Your thick head holds a beautiful brain. Thanx for porting all these modules and for all the time you've spent to do it ...while your cells were dying :smile:

**Comment by Graham-72** [comment]
> while your cells were dying

Thanks to our wonderful National Health Service my cells are no longer dying at an abnormal rate, except for effort of trying to understand other people's undocumented code - but maybe that is keeping them going? I enjoy working in the Backdrop team very much and am pleased to be a small part of such an excellent and progressive effort. Brilliant! Well done with 1.3.0!

**Comment by Graham-72** [comment]
> I believe that the common practice is to have the release title be project name + version so that it shows nicely in the GitHub notifications

@klonos thinking about this helpful advice from you, I don't think that GitHub sends me a copy of the notifications it sends out about my projects, or does it? I do see notifications for other people's work and I think 'how do they do that? Maybe they have some special software development environment?' Then I put that question to one side as one of life's many mysteries.

**Comment by Graham-72** [comment]
@klonos I have found this piece of information on GitHub which may be the answer I am looking for. It tells me how to set things so that I get the notifiations.
https://help.github.com/articles/receiving-email-notifications-for-pushes-to-a-repository/
